[project]
name = "hw5"
version = "0.1.0"
description = "Домашнее задание № 5 по предмету 'Модели ML в продакшен'."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apache-airflow>=2.9.0",
    "httpx>=0.28.1",
    "scikit-learn>=1.8.0",
]
